### Stop
DELETE http://127.0.0.1:18000/devices/00008101-000678213A9A001E/tasks
Content-Type: application/json

### Battlefield
POST http://127.0.0.1:18000/devices/00008101-000678213A9A001E/tasks
Content-Type: application/json

{
  "code": 100,
  "config": {
    "skip_pre": true,
    "potions": [
      {
        "code": "potion_timelimit",
        "quantity": 20
      },
      {
        "code": "lodestar_bead",
        "quantity": 0
      }
    ]
  }
}

### BattlefieldGacha
POST http://127.0.0.1:18000/devices/00008101-000678213A9A001E/tasks
Content-Type: application/json

{
  "code": 101,
  "config": {
    "skip_pre": true
  }
}
